module performance_test {
  module msg {
    
      typedef octet octet__1048576[1048576];
      struct Array1m {
        octet__1048576 array;

        long long time;

        unsigned long long id;
      };
    
  }; // msg
}; // performance_test
